import time

start_time = time.time()


def rev_comp(s):
    d = list(s)
    rev = []
    for word in d:
        if word == 'A':
            rev.append('T')
        if word == 'G':
            rev.append('C')
        if word == 'C':
            rev.append('G')
        if word == 'T':
            rev.append('A')
    rev.reverse()
    listToStr = ''.join(map(str, rev))
    return listToStr


s = 'TATAGGACTCCAATGAATCGCTTACAGCCCGAATCAACTGGTACGGATCTTCGGCTTGGTAGATGACTCAATCGAACCTCTGTAAATATTTTTGGGCATATATTGGACGCGGGTCCGCCCTCTTGTTACGTCAGGAGAGGCAGATTTTTCGAAGCGGGACTGTGTAATCGCCCTTTACTCCGGCGTCGGGCTGCCGGGGGTTCAAAAATATTTCGCGGAGGAAGTATTGACCTATCGATTTTGTAGAAGTGTGCCCTTCATGGAGCTCGAAAAGAAAAAGCTAACCAGCACTCCGACAGCTTGGTGCTGCGAAACGCCGCTCCTAGTTAATGGGTTTCAGCTTCTCGATTCTAGTACCGATCAACTGGTAACCAAGTGTCATCTGTTGGCTCTTCTACGTGGTTGCGTATCGAAGTTTACCATCTTGCCTCATGTTTACTAAAATGGCACCCCGGAGGCAGACGTAGAGGCTTGTCCAATGCCCGCACTTACCGGTAAGATGTGTCTGCGTAGGTATAGTATGGAGTGTCGGGCTCGCCCACTGCCCTACATGCTTGTAGAGGGAGTGCCCCATTTCCTCCGACTCAGCAGAGCATCGTAGTATCGGGAACGCATCCCACGGCTACCAACGCGCGGAAGGGAAGTTCCTCCGTCAGGGTATGATCAGATTGTATTCCACCCGTAAGCTATTGAGGTTAGACTGAAATTTGTGCGAATCTATGAGTTGCCGATCAACAGGCCACCAAAAATCATCCAGGGCCGTCAGTACAGTTTGCTTAGGCGAAGCGCATATACAGCGTGCACTGCGTCTACCCTCGTTCACTATGCCCCAGCTGACTTAAAGGAACTGCGCCCACTGAACGCTAAGGACTGACGTGCGTTCACAGGAAGAGAGAAGTTCAGGACCAGCCCTGCTGAACGGGACGTCCCCATGCCGATGTAAGATAACTTAAAGGTGATAATATATGAGCAATCCTAGGTGTATA'
cut = [12, 10, 8, 6, 4]
for a in range(5):
    leng = len(s) - cut[a]
    for i in range(leng + 1):
        x = s[i:(i + cut[a])]
        if x == rev_comp(x):
            print("%d %d" % (i + 1, cut[a]))
print("--- %s seconds ---" % (time.time() - start_time))