s = 'TATGTTTTAAGTCATGCTCACTTCTGGCTGGATCCCCACGAGTTAGTGACAACAGCTGGGCAAAGACTCCAATATTCAGGTAGTGCAGGAACTTGCTTTCTTGAATCCTAGAGCCAAATGTACTGTGGAAGCAAATAGACTATCTAACAAGAACAAGAACCTCGGTTGAATGTTAGAAAACCCAGATTATAGGTGGAACTGAACAAACTGGAACGGGACACATTTGAAGTTTCTAAAGAACTATGCGCTTCACAGTCGATAGATTAATGACAACGACAACCCATTCATCGCATAAGGATTATCCATAGGAGTCGACTATAAACAAGGCCCAGGTGCCCAGTGAAGTCTTTGCTTCCTGAGGGCCACATCCTATGGCTCGATTGGGCTGGCTGCCAGGGACAGTGCTCCTCGATGGCTCACACCTGAAACAACTATTAGGCCTTCCGAGTTGGAGCAACATAGCGCCAGCACTATTCCTAACGCCCGCGGCAACTACTGCGGCAACTTGGGGTTACAAATTTAAAGCAGACACCGACTCATAAACGATAAGAATGCGAGTTGCAGTGTTCCTGGCCTCTCGTTTGTGACTACTCATCGCTCACGGGAAAGTCGCATTGTCACCTGTCTGAGAACCTGTATCCCGCGGCGGTCACAAGGCGCCAAGCCCTCCATATAAACCGCGTATTGCATCGACTGTACTTACCAGCGTGTCATTCCAAATGAAATTTAGTAACATAAAAGAGCGTACTACCGAGTGGATGCTATCGTGGTTAGTAGGGAACGTTGACAATGGTATTTAGAAGAGGCGAGCCGAGCATTAAGTTTCCCGAGGCTTTAGGGCTGAATGCGGGTACTCCCCCGATTACTCCTCATCCGCCTCCCCTCACTGCCGGATGATCATTTCCGACTTCGTGCTCCTTCTGCCCTTAACCCGCGGTAACGTCGTAGTGACTGATCCCCGGCCACTCTGAACCTGGTAGCGTATAACCACCTG'

d = list(s)

rev = []

for word in d:
    if word == 'A':
        rev.append('T')
    if word == 'G':
        rev.append('C')
    if word == 'C':
        rev.append('G')
    if word == 'T':
        rev.append('A')

rev.reverse()
for words in rev:
    print(words, end='')
